### ISSUE TITLE
Doesn't install VMware-tools on RHEL

### ISSUE THREAD

**Issue by nmadhok** [saltstack-formulas/vmware-tools-formula#3]
Has this been tested to work? @techhat 
This surely doesn't have the code to do it for RHEL systems.  
I will modify it soon to work it with RHEL systems but just wanted to ask if this works with other systems?

**Comment by alias454** [comment]
I uploaded a new vmware-tools formula that should work with RHEL based systems. Can you take a look at this to see if it works for you if you haven't already devised another solution?

Regards,
Brandon
