### ISSUE TITLE
Use VMware's "Operating System Specific Packages" (OSP) or open-vm-tools

### ISSUE THREAD

**Issue by 0xf10e** [saltstack-formulas/vmware-tools-formula#4]
[Here's the install guide](https://packages.vmware.com/tools/docs/manuals/osp-esxi-51-install-guide.pdf) for VMware's official packages for
- CentOS 4.0 through 6.x
- RHEL 3.0 through 6.x
- SUSE Linux Enterprise Server 9 through 11
- SUSE Linux Enterprise Desktop 10 through 11
- Ubuntu Linux 8.04 through 12.04
  (See [here](https://www.vmware.com/support/packages) for the list)

Where available VMware supports and recommends usage of the open-vm-tools packages provided by the OS Vendor. The [VMware KB entry 2073803](http://kb.vmware.com/kb/2073803) has this list:
- Fedora 19 and later releases
- Debian 7.x and later releases
- openSUSE 11.x and later releases
- Recent Ubuntu releases (12.04 LTS, 13.10 and later)
- Red Hat Enterprise Linux 7.0 and later releases
- CentOS 7 and later releases
- Oracle Linux 7 and later releases
- SUSE Linux Enterprise 12 and later releases 

I think by default those packages should be used. If no packages are available or some pillar-key like 'vmware-tools:from_source' is set to True we can still try to install the vmware-tools from source.

**Comment by alias454** [comment]
While I have not tested on all variations of the above listed operating systems, I can verify this will either install the open-vm-tools package or utilize the tar.gz based on OS version. I could try testing with a Debian system once I can get a chance to spin up a new VM.

**Comment by 0xf10e** [comment]
Oh, wow, I totally forgot I opened this issue!

I'll see if I have a few minutes today to add Ubuntu to the mix.

I still think OSP support would be useful but most of the supported releases are pretty old by now anyway so that's a lower priority.

Also in case of installation from source any packages should be removed.

We'll see how much I get done myself ;)

**Comment by aboe76** [comment]
@0xf10e and @alias454 please see #9

**Comment by alias454** [comment]
@aboe76 Closing this since the latest PR should allow any additional OS additions that someone would need.
